import { useEffect, useState } from "react";
import { Card, PageHeader, Spinner } from "../components/ui";
import { useCachedGet } from "../hooks/useCachedGet";

interface NetworkInfo {
  hostname: string;
  port: number;
  primary_url: string | null;
  mdns_url: string | null;
  app_url: string | null;
  app_qr_svg: string | null;
  other_urls: string[];
  ignored: string[];
  qr_svg: string | null;
  mdns_qr_svg: string | null;
  shared_on_network: boolean;
  camera_node_url: string | null;
  camera_node_qr_svg: string | null;
  cctv_url: string | null;
  cctv_qr_svg: string | null;
  mobile_recognition_url: string | null;
  mobile_recognition_qr_svg: string | null;
}

export default function Connect() {
  const [copied, setCopied] = useState("");
  // On port 80 the browser reports an EMPTY port, so defaulting to 8000 here
  // would report the wrong address on exactly the setup this is meant for.
  const port = window.location.port || (window.location.protocol === "https:" ? 443 : 80);
  const { data: info, refresh: load } = useCachedGet<NetworkInfo>(`/api/network?port=${port}`);

  useEffect(() => {
    // The address changes whenever the Wi-Fi does, so re-read it rather than
    // leaving a stale QR code on screen that sends people nowhere.
    const t = window.setInterval(load, 10000);
    return () => window.clearInterval(t);
  }, [load]);

  function copy(text: string) {
    navigator.clipboard?.writeText(text).then(
      () => {
        setCopied(text);
        window.setTimeout(() => setCopied(""), 2000);
      },
      () => {},
    );
  }

  if (!info) return <Spinner label="Finding this computer's address..." />;

  // Reconize publishes recognize.local for itself; the machine name is the
  // fallback for when zeroconf is unavailable.
  const stableUrl = info.app_url ?? info.mdns_url ?? "";
  const stableQr = info.app_qr_svg ?? info.mdns_qr_svg;

  return (
    <div>
      <PageHeader
        title="Connect a phone or another PC"
        subtitle="Anyone on the same Wi-Fi can open Reconize here. The address is re-checked every few seconds, so it stays right if the network changes."
      />

      {info.port !== 80 && (
        <Card className="mb-4">
          <div className="text-sm text-gray-700">
            Reconize is on port <strong>{info.port}</strong>, so the address includes{" "}
            <span className="font-mono">:{info.port}</span>. Port 80 would let people type just{" "}
            <span className="font-mono">{(info.app_url ?? info.mdns_url ?? "http://recognize.local").replace(/:\d+$/, "")}</span>{" "}
            with no port at all — it was either in use or blocked when Reconize started.
          </div>
        </Card>
      )}

      {!info.shared_on_network && (
        <Card className="border-amber-200 bg-amber-50 mb-4">
          <div className="font-semibold text-amber-900">Not shared on the network yet</div>
          <div className="text-sm text-gray-700 mt-1">
            Reconize is only listening on this computer, so the address below will not answer from
            another device. Start it with <span className="font-mono">start-network.bat</span> instead
            of <span className="font-mono">start.bat</span>, and allow Python through the Windows
            Firewall on <strong>private networks</strong> when prompted.
          </div>
        </Card>
      )}

      <div className="grid md:grid-cols-2 gap-4">
        <Card>
          <h2 className="font-semibold text-gray-900 mb-1">Scan this with a phone</h2>
          <p className="text-xs text-gray-400 mb-4">
            The phone must be on the same Wi-Fi as this computer.
          </p>
          {info.qr_svg ? (
            <div className="flex flex-col items-center">
              <div
                className="p-4 bg-white rounded-xl border border-gray-200"
                // The SVG is generated by our own backend, not user input.
                dangerouslySetInnerHTML={{ __html: info.qr_svg }}
              />
              <button
                onClick={() => copy(info.primary_url ?? "")}
                className="mt-4 font-mono text-lg text-indigo-700 hover:underline"
                title="Click to copy"
              >
                {info.primary_url ?? "No network address found"}
              </button>
              {copied === info.primary_url && (
                <div className="text-xs text-green-600 mt-1">Copied</div>
              )}
            </div>
          ) : (
            <div className="text-sm text-gray-500">
              No network address was found. This computer may not be connected to Wi-Fi.
            </div>
          )}
        </Card>

        <Card>
          <h2 className="font-semibold text-gray-900 mb-1">Name that does not change</h2>
          <p className="text-xs text-gray-400 mb-4">
            The address above changes whenever this computer joins a different Wi-Fi. This name does
            not, so it is the one worth writing down.
          </p>
          {stableUrl ? (
            <div className="flex flex-col items-center">
              {stableQr && (
                <div
                  className="p-4 bg-white rounded-xl border border-gray-200"
                  dangerouslySetInnerHTML={{ __html: stableQr }}
                />
              )}
              <button
                onClick={() => copy(stableUrl)}
                className="mt-4 font-mono text-lg text-indigo-700 hover:underline"
                title="Click to copy"
              >
                {stableUrl}
              </button>
              {copied === stableUrl && <div className="text-xs text-green-600 mt-1">Copied</div>}
              {info.app_url && info.mdns_url && (
                <div className="text-xs text-gray-400 mt-1">
                  also <span className="font-mono">{info.mdns_url}</span>
                </div>
              )}
              <p className="text-xs text-gray-400 mt-3 text-center">
                Works on iPhone, iPad, Mac and Windows. Android often cannot open{" "}
                <span className="font-mono">.local</span> addresses — use the QR code on the left
                for Android phones.
              </p>
            </div>
          ) : (
            <div className="text-sm text-gray-500">
              This network does not resolve <span className="font-mono">.local</span> names, so use
              the address on the left.
            </div>
          )}
        </Card>
      </div>

      <Card className="mt-4">
        <h2 className="font-semibold text-gray-900 mb-2">What works from another device</h2>
        <div className="grid sm:grid-cols-2 gap-x-6 gap-y-1 text-sm">
          <div className="text-gray-700">✓ Cameras — start and stop recording</div>
          <div className="text-gray-700">✓ Participants, Import, PDPA</div>
          <div className="text-gray-700">✓ Reports, Activities, Event Photos</div>
          <div className="text-gray-700">✓ Attendance and history</div>
          <div className="text-amber-700 sm:col-span-2 mt-1">
            ✕ Kiosk face scanning needs the device's own camera, which browsers only allow over
            https or on this computer itself. Recording the 7 cameras still works from a phone,
            because this computer owns those cameras — the phone is only the remote control.
          </div>
        </div>
      </Card>

      <div className="mt-6">
        <h2 className="text-sm font-semibold text-gray-500 uppercase mb-2">Distributed camera nodes</h2>
        <div className="grid md:grid-cols-3 gap-4">
          <QrLinkCard
            title="Windows PC → Camera Node"
            hint="Opens the station setup form on that PC."
            url={info.camera_node_url}
            svg={info.camera_node_qr_svg}
            onCopy={copy}
            copied={copied}
          />
          <QrLinkCard
            title="Phone / iPad → Camera Recognition"
            hint="Central runs the recognition — no Local Agent needed."
            url={info.mobile_recognition_url}
            svg={info.mobile_recognition_qr_svg}
            onCopy={copy}
            copied={copied}
          />
          <QrLinkCard
            title="CCTV — all camera nodes"
            hint="Live view of every registered station."
            url={info.cctv_url}
            svg={info.cctv_qr_svg}
            onCopy={copy}
            copied={copied}
          />
        </div>
      </div>

      {(info.other_urls.length > 0 || info.ignored.length > 0) && (
        <Card className="mt-4">
          <h2 className="font-semibold text-gray-900 mb-2">Other addresses</h2>
          {info.other_urls.length > 0 && (
            <div className="text-sm text-gray-600 mb-2">
              Also reachable:{" "}
              {info.other_urls.map((u) => (
                <span key={u} className="font-mono mr-3">{u}</span>
              ))}
            </div>
          )}
          {info.ignored.length > 0 && (
            <div className="text-xs text-gray-400">
              Ignored (virtual adapters that no phone can reach):{" "}
              {info.ignored.join(", ")}
            </div>
          )}
        </Card>
      )}
    </div>
  );
}

function QrLinkCard({
  title, hint, url, svg, onCopy, copied,
}: {
  title: string; hint: string; url: string | null; svg: string | null;
  onCopy: (text: string) => void; copied: string;
}) {
  return (
    <Card>
      <h3 className="font-semibold text-gray-900 text-sm mb-1">{title}</h3>
      <p className="text-xs text-gray-400 mb-3">{hint}</p>
      {svg && url ? (
        <div className="flex flex-col items-center">
          <div className="p-3 bg-white rounded-xl border border-gray-200" dangerouslySetInnerHTML={{ __html: svg }} />
          <button onClick={() => onCopy(url)} className="mt-3 font-mono text-xs text-indigo-700 hover:underline break-all text-center" title="Click to copy">
            {url}
          </button>
          {copied === url && <div className="text-xs text-green-600 mt-1">Copied</div>}
        </div>
      ) : (
        <div className="text-sm text-gray-500">No network address found.</div>
      )}
    </Card>
  );
}
